baseURL: "https://devcui.github.io/intro/"
title: "intro"
paginate: 10
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: true
enableEmoji: true
googleAnalytics: UA-213464061-1
defaultContentLanguage: cn
minify:
  disableXML: true
  minifyOutput: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
languages:
  cn:
    languageName: ":cn:"
    languageAltTitle: 中文
    weight: 1
    title: 神奇宝贝大师的旅行日记
menu:
  main:
    - name: 列表
      identifier: posts
      url: posts
      weight: 9
    - name: 分类
      identifier: categories
      url: categories
      weight: 10
    - name: 标签
      identifier: tags
      url: tags
      weight: 20
    - name: 系列
      identifier: series
      url: series
      weight: 30
    - name: 归档
      identifier: archives
      url: archives
      weight: 40
    - name: 冠军
      url: "resume"
      weight: 50
    - name: 救助可达鸭
      url: "psyduck"
      weight: 60
    - name: 已抓住图鉴
      url: "https://zukan.pokemon.co.jp/"
      weight: 70
